const actionType = {
  GET_ACTIVITIES_SUCCESS: "GET_ACTIVITIES_SUCCESS",
  GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
  GET_TIMESHEET_SUCCESS: "GET_TIMESHEET_SUCCESS",
  UPDATE_CONFIG_SUCCESS: "UPDATE_CONFIG_SUCCESS",
}
export default actionType;